### ISSUE TITLE
TypeError: string is not a function

### ISSUE THREAD

**Issue by hodonsky** [jessetane/multiparser#1]
``` bash
/usr/src/utilities/node_modules/multiparser/lib/transformer.js:30
      cb()
      ^
TypeError: string is not a function
  at push (/usr/src/utilities/node_modules/multiparser/lib/transformer.js:30:7)
```

So I investigated a little, and it looks like when it hits this point `cb === "buffer" && typeof cb === "string"`
... I started using the basic example in the README.md, however, I get this error every time.

My Deps:

```
node@0.12.2
koa@0.20.0
koa-router@5.1.2
multiparser@0.0.4 (I cloned 0.0.5 just to be sure)

```

**Comment by jessetane** [comment]
I didn't actually realize people were using this library! I wrote this a long time ago mostly for educational purposes and since then a few (I assume) better alternatives have appeared:

https://github.com/andrewrk/node-multiparty
https://github.com/mscdex/busboy

Were you aware of these / is there a reason you chose this library instead? If there is a compelling reason to look back into this I am willing to help..

**Comment by hodonsky** [comment]
Well thanks for the suggestions, npmjs doesn't really make finding a good up to date dependancy easy. I liked your project for size, and simplicity. I will probably look into going with busboy. I prefer to have 0 dependancies, but that's a nightmare if you want to do anything with any kind of haste. Thanks again.

**Comment by jessetane** [comment]
Gotcha, thanks for following up. I will deprecate this project on npm so as to try and avoid further confusion.

**Comment by hodonsky** [comment]
Totally a good idea
